spring:
  datasource:
    username: root
    password: 12345 # local
#    password: PwUYtotGFZVdDKrY

eureka:
  client:
    service-url:
      defaultZone: http://172.16.0.156:8761/eureka
# eureka server? ??